name: CI
on:
  push:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      node-version: [10.x, 12.x 14.x]
    steps:
      - actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses; actions/setp-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm --version