name: IAC Deployment.
on:
  pull_request:
    types: [labeled]
    branches: [feature/github-actions]

env:
  AZURE_RESOURCE_GROUP: cgc-azure-resume
  AZURE_LOCATION: '"Central US"'

jobs:
  setup-up-azure-resources:
    runs-on: ubuntu-latest
    
    if: contains(github.event.pull_request.labels.*.name, 'Create')
    
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Create Azure Resource Group
        if: success()
        run: |
          pwd
          az group create --location ${{ env.AZURE_LOCATION }} \
            --name ${{ env.AZURE_RESOURCE_GROUP }} \
            --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
      - name: Create Storage Account in Resource Group
        if: success()
        working-directory: ./devops
        run: |
          pwd
          az deployment group create -g ${{ env.AZURE_RESOURCE_GROUP }} -n 'acg-resume-az-stge-account-deployment' \
            --template-file storage-account-template.json \
            --parameters storage-account-parameters.json
            
  destroy-azure-resources:
    runs-on: ubuntu-latest
    
    if: contains(github.event.pull_request.labels.*.name, 'Destroy')
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Destroy Azure Environment
        if: success()
        run: |
          az group delete --name ${{ env.AZURE_RESOURCE_GROUP }} \
            --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} \
            --yes
    
